project/config/urls.py
"""
URL Configuration for project
"""


from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path

urlpatterns = []

urlpatterns += i18n_patterns(
    path(settings.ADMIN_URL, admin.site.urls),
    path("", include("shorted.urls", namespace="shorted")),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # Serve static and media files for development server
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

    import debug_toolbar

    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

project/shorted/urls.py
from django.urls import path
from django.views.generic import DetailView, TemplateView
from shorted import views
from shorted.models import Video

app_name = "shorted"

urlpatterns = [
    path(
        "",
        views.HomeView.as_view(template_name="pages/home.html"),
        name="home",
    ),
    path(
        "impressum",
        TemplateView.as_view(
            template_name="pages/impressum.html",
        ),
        name="impressum",
    ),
    path(
        "about",
        TemplateView.as_view(
            template_name="pages/about.html",
        ),
        name="about",
    ),
    path(
        "video-detail/<int:pk>",
        DetailView.as_view(
            model=Video,
            template_name="pages/video-detail.html",
        ),
        name="video_detail",
    ),
    path(
        "idea-form",
        views.IdeaFormCreate.as_view(
            template_name="pages/idea-form.html",
        ),
        name="idea-form",
    ),
]

project/shorted/models.py
import logging

import requests
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django_q.tasks import async_chain, async_task
from model_utils.models import TimeStampedModel


class Video(TimeStampedModel):
    """
    Model representing a video.
    """

    preview_image = models.ImageField(max_length=255, blank=True)
    preview_video_path = models.CharField(max_length=255, blank=True)
    title = models.CharField(max_length=255, blank=True)
    video_url = models.URLField(
        blank=True,
        default="",
        help_text=_("Link zum Video."),
    )
    pinned = models.BooleanField(
        default=False,
        help_text=_(
            'Anwählen, falls dieses Video als "Gewinner" angepinnt werden soll.'
        ),
    )
    archive = models.BooleanField(
        default=False,
        help_text=_("Anwählen, falls dieses Video im Archiv erscheinen soll."),
    )
    oembed_data = models.JSONField(
        blank=True,
        null=True,
        help_text=_("JSON-Objekt mit den Daten des Videos."),
    )

    def save(self, *args, create_preview=True, **kwargs):
        """
        Override the save method to fetch the oEmbed data for Vimeo videos.
        """
        logger = logging.getLogger(__name__)

        if create_preview and self.video_url.startswith("https://vimeo.com/"):
            logger.log(
                logging.INFO, f"Fetching oEmbed data for Vimeo video {self.video_url}"
            )
            # Construct the oEmbed API URL for the Vimeo video
            api_url = f"https://vimeo.com/api/oembed.json?url={self.video_url}&responsive=true"

            # Make a request to the Vimeo oEmbed API to fetch the oEmbed data
            headers = {"Referer": "unibas.ch"}
            response = requests.get(api_url, headers=headers, timeout=10)

            # If the request was successful, save the oEmbed data to the video object
            if response.status_code == 200:
                oembed_data = response.json()
                logger.log(logging.INFO, oembed_data)
                self.oembed_data = oembed_data
                # Create a video preview gif
                async_chain(
                    [
                        (
                            "shorted.services.download_video",
                            (self.oembed_data["video_id"],),
                        ),
                        ("shorted.services.create_video_preview", (self,)),
                        #    ("shorted.services.delete_source_video", (self.oembed_data["video_id"],)),
                    ]
                )

        super().save(*args, **kwargs)

    def get_absolute_url(self):
        """Get absolute url."""
        return reverse("shorted:video_detail", kwargs={"pk": self.pk})

    def __str__(self):
        """To string method."""
        return self.title


def validate_email_domain(value):
    """
    Validate that the email address is from the unibas.ch domain.
    """
    domain = value.split("@")[-1]
    if domain != "unibas.ch" and domain != "stud.unibas.ch":
        raise ValidationError(
            _(
                "Bitte geben Sie eine gültige @unibas.ch oder @stud.unibas.ch E-Mail Adresse ein."
            )
        )


class Idea(TimeStampedModel):
    """
    Model to record students ideas for new videos.
    """

    email_address = models.EmailField(
        blank=False,
        verbose_name=_("E-Mail Adresse"),
        help_text=_("Ihre @unibas.ch oder @stud.unibas.ch E-Mail Adresse"),
        validators=[validate_email_domain],
    )
    first_name = models.CharField(
        verbose_name=_("Vorname"),
        max_length=40,
        blank=False,
        help_text=_("Ihr Vorname"),
    )
    last_name = models.CharField(
        verbose_name=_("Nachname"),
        max_length=40,
        blank=False,
        help_text=_("Ihr Nachname"),
    )
    idea = models.TextField(
        verbose_name=_("Frage"),
        blank=False,
        help_text=_("Frage, die das Erklärvideo beantworten sollte"),
    )
    answer = models.TextField(
        verbose_name=_("Antwort"),
        blank=False,
        help_text=_(
            "Kurzer Abschnitt, der die Antwort auf ihre Frage gibt."
            "(Bitte beachten Sie, dass das Team New Media Center das Drehbuch der Ideen erstellen wird,"
            "die ausgewählt werden. Sie sehen aber das Drehbuch, bevor wir es umsetzen)."
        ),
    )
    consent_to_present_personally = models.BooleanField(
        verbose_name=_("Einverständnis"),
        help_text=_(
            "Ich wäre bereit, im Video Abschnitte vor der Kamera zu präsentieren."
        ),
    )
    field_of_study = models.CharField(
        verbose_name=_("Studienfach"),
        blank=False,
        help_text=_("Ihr Studienfach"),
    )
    idea_processed = models.BooleanField(
        default=False,
        help_text=_("Die Idee wurde überprüft."),
    )

    def save(self, *args, **kwargs):
        """
        Override the save method to send an email to the user.
        """
        is_new = self.pk is None
        super().save(*args, **kwargs)

        # Send an email to the user when the idea is created
        if is_new:
            async_task(
                "shorted.services.send_email_confirmation", self.email_address, self.id
            )

    def get_success_url(self):
        """Return the url to redirect to after a successful submission."""
        return reverse("shorted:home")

    def __str__(self):
        """Return the string representation of the object."""
        return f"{self.first_name} {self.last_name}: \n{self.idea}"


class StaticText(TimeStampedModel):
    """
    Model to create static texts.
    the value of text_position can be used with the custom template tag {% get_static_text text_position %}
    """

    text_position = models.CharField(max_length=20, blank=False, db_index=True)
    content = models.TextField(
        max_length=None,
        blank=True,
        help_text=_("Text der an dieser Stelle angezeigt werden soll."),
    )

    def __str__(self):
        """Return the string representation of the object."""
        return self.text_position

project/shorted/forms.py
"""
Forms for the shorted app.
"""
from django import forms
from shorted import models


class IdeaForm(forms.ModelForm):
    """Idea form."""

    def clean(self):
        """Clean form data."""
        cleaned_data = super().clean()
        cleaned_data["email_address"] = cleaned_data["email_address"].lower()
        return cleaned_data

    class Meta:
        """Meta class."""

        model = models.Idea
        fields = "__all__"
        exclude = ("idea_processed",)

project/shorted/views.py
from django.contrib import messages
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from shorted import forms
from shorted.models import Idea, Video


# from watson import SearchView
class HomeView(TemplateView):
    """Home view."""

    def get_context_data(self, **kwargs):
        """Return context data."""
        context = super().get_context_data(**kwargs)
        context["pinned_videos"] = Video.objects.filter(pinned=True)
        context["archived_videos"] = Video.objects.filter(pinned=False)
        return context


class IdeaFormCreate(CreateView):
    """Course create view."""

    model = Idea
    form_class = forms.IdeaForm
    template_name = "pages/idea-form.html"

    def get_success_message(self, cleaned_data):
        """Return success message."""
        return _("Ihre Idee wurde erfolgreich abgeschickt.")

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        self.object = form.save()
        messages.success(self.request, self.get_success_message(form.cleaned_data))
        return super().form_valid(form)

    def get_success_url(self):
        """Return success url."""
        return reverse("shorted:home")

project/shorted/templates/components/footer.html
{% load i18n %}
<footer id="footer" class="navbar bottom bg-light-grey mt-3">
    <div class="container justify-content-center">
        <ul class="nav flex-row flex-wrap align-items-center">
            <li class="nav-item">
                <a class="nav-link footer-link text-white"
                   href="{% url 'shorted:impressum' %}">
                    <span class="d-none d-md-inline">{% trans "Impressum" %}</span>
                    <span class="d-md-none" style="font-size: xx-large">§</span>
                </a>
            </li>
            <!--li class="nav-item">
                <a class="nav-link footer-link text-white" href="{% url 'shorted:about' %}" data-title="{% trans 'Info' %}" data-bs-target="#modal">
                    <span class="d-none d-md-inline">{% trans "Info" %}</span>
                    <span class="d-md-none" style="font-size: xx-large">
                        <i class="bi bi-info-circle"></i>
                    </span>
                </a>
            </li--->
        </ul>
    </div>
</footer>

project/shorted/templates/components/header.html
{% load static i18n utils %}
<header id="header">
    <div class="nmc-bg-color-anthracite">
        <div class="container">
            <div class="row offset-1">
                <ul class="nav">
                    <li class="nav-item">
                    <a class="nav-link text-white"
                       href="{% url 'shorted:home' %}"
                       title="{% trans 'Übersicht' %}"><span class="d-none d-md-inline">{% trans 'Übersicht' %}</span><span class="d-md-none"><i class="bi bi-house"></i></span>
                </a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle text-white"
                   data-bs-toggle="dropdown"
                   href="#"
                   role="button"
                   aria-expanded="false">{% trans 'Sprache' %}</a>
                <ul class="dropdown-menu">
                    <li>
                        <a class="dropdown-item" href="{% translate_url 'de' %}">Deutsch</a>
                    </li>
                    <li>
                        <a class="dropdown-item" href="{% translate_url 'en' %}">English</a>
                    </li>
                </ul>
            </li>
            <div class="me-auto"></div>
        </ul>
    </div>
</div>
</div>
<!-- Brand container -->
<div class="uni-main-wrapper">
    <div class="container">
        <div class="uni-logo row">
            <div class="col-12 offset-1">
                <a href="/">
                    {% if LANGUAGE_CODE == 'en' %}
                        <img src="{% static 'images/uni-basel-logo-en.svg' %}"
                             alt="University of Basel">
                    {% endif %}
                    {% if LANGUAGE_CODE == 'fr' %}
                        <img src="{% static 'images/uni-basel-logo-en.svg' %}"
                             alt="University of Basel">
                    {% endif %}
                    {% if LANGUAGE_CODE == 'de' %}
                        <img src="{% static 'images/uni-basel-logo-de.svg' %}"
                             alt="Universität Basel">
                    {% endif %}
                </a>
            </div>
        </div>
    </div>
</div>
</header>